export enum RoleEnum {
    ADMIN = 'ADMIN',
    MANAGER = 'MANAGER',
    ACCOUNTANT = 'ACCOUNTANT',
    ORGANIZER='ORGANIZER',
    TRAINER ='TRAINER',
    STUDENT='STUDENT',
    GUEST='GUEST',
    SUPPORT_ENGINEER='SUPPORT_ENGINEER'
}